<?php

namespace AppBundle\Repository;

/**
 * canchaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class canchaRepository extends \Doctrine\ORM\EntityRepository
{
}
