<?php

namespace AppBundle\Repository;

/**
 * clienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clienteRepository extends \Doctrine\ORM\EntityRepository
{
}
