<?php

namespace AppBundle\Repository;

/**
 * horariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class horariosRepository extends \Doctrine\ORM\EntityRepository
{
}
