<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
/**
 * reservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class reservaRepository extends \Doctrine\ORM\EntityRepository
{

    function obtenerNativeQueryDeReserva($nombreCancha,$fechaActual)
    {
        $em = $this->getEntityManager();
        
        $rsm = new ResultSetMapping();
        // Las columnas que necesitás
        $rsm->addScalarResult('fecha', 'fecha');
        $rsm->addScalarResult('nombreCancha', 'nombreCancha');
        
        // Consulta nativa
        // Traigo las fechas segun la cancha desde la fecha actual hasta el 2022
        $query = $em->createNativeQuery(
            "SELECT * FROM reserva WHERE nombreCancha ='${nombreCancha}' AND fecha BETWEEN '${fechaActual}' AND '2026-12-31 00:00:00'",
            $rsm
        );

        return $query->getResult();
    }
}
