<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
/**
 * reservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class reservaRepository extends \Doctrine\ORM\EntityRepository
{

    function obtenerNativeQueryDeReserva($tamano,$fechaActual)
    {
        $em = $this->getEntityManager();
        
        $rsm = new ResultSetMapping();
        // Las columnas que necesitás
        $rsm->addScalarResult('fecha_reserva', 'fecha_reserva');
        $rsm->addScalarResult('hora', 'hora');
        $rsm->addScalarResult('tamano', 'tamano');
        
        // Consulta nativa
        // Traigo las fechas segun la cancha desde la fecha actual hasta el 2022
        $query = $em->createNativeQuery(
            "SELECT * FROM reserva WHERE tamano ='${tamano}'AND fecha_reserva BETWEEN '${fechaActual}' AND '2023-12-31'",
            $rsm
        );

        return $query->getResult();
    }
}
