<?php

namespace AppBundle\Repository;

/**
 * tipo_montoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipoMontoRepository extends \Doctrine\ORM\EntityRepository
{
}
